-- ============================================================
-- Migration 0007: schema sync (shared/schema.ts vs migrations 0000..0006)
-- Generated by drizzle-kit generate, then post-processed to be purely
-- additive and idempotent so it is safe on a DB at ANY prior state
-- (0000..0006 applied, or provisioned via db:push):
--   * CREATE TABLE / CREATE [UNIQUE] INDEX  -> IF NOT EXISTS
--   * ADD COLUMN                             -> IF NOT EXISTS
--   * ADD CONSTRAINT                         -> DO $$ ... duplicate_object guard
--   * all DROP / ALTER COLUMN statements emitted by the generator removed
-- ============================================================
CREATE TABLE IF NOT EXISTS "flow_test_queue" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"flow_id" varchar NOT NULL,
	"to_phone" text NOT NULL,
	"status" text DEFAULT 'waiting' NOT NULL,
	"call_id" varchar,
	"error_message" text,
	"processed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "google_calendar_credentials" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"token_expiry" timestamp NOT NULL,
	"connected_email" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "google_calendar_credentials_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "google_sheets_credentials" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"token_expiry" timestamp NOT NULL,
	"connected_email" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "google_sheets_credentials_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "phone_release_retry_queue" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phone_number_id" varchar NOT NULL,
	"provider" text NOT NULL,
	"provider_sid" text NOT NULL,
	"user_id" varchar,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"next_retry_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_feedback" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"type" text NOT NULL,
	"subject" text NOT NULL,
	"description" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"priority" text DEFAULT 'medium',
	"admin_response" text,
	"responded_by" varchar,
	"responded_at" timestamp,
	"page_url" text,
	"user_agent" text,
	"screenshot" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "messaging_email_enabled" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "messaging_whatsapp_enabled" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "messaging_email_template" text;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "messaging_whatsapp_template" text;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "messaging_whatsapp_variables" text;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "expressive_mode" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "turn_timeout" double precision DEFAULT 1.5;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "engine" text;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "openai_model" text;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "sarvam_voice" text;
--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN IF NOT EXISTS "voice" text;
--> statement-breakpoint
ALTER TABLE "appointment_settings" ADD COLUMN IF NOT EXISTS "sync_to_google_calendar" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "status_reason" varchar(500);
--> statement-breakpoint
ALTER TABLE "appointments" ADD COLUMN IF NOT EXISTS "google_calendar_event_id" varchar(255);
--> statement-breakpoint
ALTER TABLE "calls" ADD COLUMN IF NOT EXISTS "agent_id" varchar;
--> statement-breakpoint
ALTER TABLE "calls" ADD COLUMN IF NOT EXISTS "engine_type" text;
--> statement-breakpoint
ALTER TABLE "calls" ADD COLUMN IF NOT EXISTS "credits_used" integer DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "retry_max_attempts" integer DEFAULT 3;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "retry_interval_minutes" integer DEFAULT 60;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "retry_on_no_answer" boolean DEFAULT true;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "retry_on_busy" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "retry_on_failed" boolean DEFAULT false;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "batch_job_history" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "current_retry_pass" integer DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN IF NOT EXISTS "attempt_count" integer DEFAULT 1;
--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN IF NOT EXISTS "last_attempt_at" timestamp;
--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN IF NOT EXISTS "next_retry_at" timestamp;
--> statement-breakpoint
ALTER TABLE "phone_numbers" ADD COLUMN IF NOT EXISTS "credentials_synced_at" timestamp;
--> statement-breakpoint
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "voice_provider" text DEFAULT 'openai' NOT NULL;
--> statement-breakpoint
ALTER TABLE "plivo_phone_numbers" ADD COLUMN IF NOT EXISTS "stripe_subscription_id" text;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "sip_trunk_id" varchar;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "openai_call_id" varchar(255);
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "elevenlabs_conversation_id" varchar(255);
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "credits_used" numeric(10, 2) DEFAULT '0';
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "recording_url" text;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "transcript" jsonb;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "ai_summary" text;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "sentiment" varchar(50);
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "classification" varchar(50);
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "sip_headers" jsonb;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
--> statement-breakpoint
ALTER TABLE "sip_calls" ADD COLUMN IF NOT EXISTS "answered_at" timestamp;
--> statement-breakpoint
ALTER TABLE "sip_phone_numbers" ADD COLUMN IF NOT EXISTS "eleven_labs_credential_id" varchar;
--> statement-breakpoint
ALTER TABLE "sip_phone_numbers" ADD COLUMN IF NOT EXISTS "credentials_synced_at" timestamp;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "flow_test_queue" ADD CONSTRAINT "flow_test_queue_flow_id_flows_id_fk" FOREIGN KEY ("flow_id") REFERENCES "public"."flows"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "user_feedback" ADD CONSTRAINT "user_feedback_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "user_feedback" ADD CONSTRAINT "user_feedback_responded_by_users_id_fk" FOREIGN KEY ("responded_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "phone_release_retry_queue_next_retry_at_idx" ON "phone_release_retry_queue" USING btree ("next_retry_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "phone_release_retry_queue_phone_number_id_idx" ON "phone_release_retry_queue" USING btree ("phone_number_id");
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "sip_calls" ADD CONSTRAINT "sip_calls_sip_trunk_id_sip_trunks_id_fk" FOREIGN KEY ("sip_trunk_id") REFERENCES "public"."sip_trunks"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "sip_calls" ADD CONSTRAINT "sip_calls_sip_phone_number_id_sip_phone_numbers_id_fk" FOREIGN KEY ("sip_phone_number_id") REFERENCES "public"."sip_phone_numbers"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "sip_calls" ADD CONSTRAINT "sip_calls_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "sip_phone_numbers" ADD CONSTRAINT "sip_phone_numbers_eleven_labs_credential_id_eleven_labs_credentials_id_fk" FOREIGN KEY ("eleven_labs_credential_id") REFERENCES "public"."eleven_labs_credentials"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_user_id_idx" ON "calls" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_campaign_id_idx" ON "calls" USING btree ("campaign_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_contact_id_idx" ON "calls" USING btree ("contact_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_status_idx" ON "calls" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_created_at_idx" ON "calls" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_twilio_sid_idx" ON "calls" USING btree ("twilio_sid");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_elevenlabs_conversation_id_idx" ON "calls" USING btree ("elevenlabs_conversation_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_agent_id_idx" ON "calls" USING btree ("agent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaigns_user_id_idx" ON "campaigns" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaigns_status_idx" ON "campaigns" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaigns_deleted_at_idx" ON "campaigns" USING btree ("deleted_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "campaigns_agent_id_idx" ON "campaigns" USING btree ("agent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contacts_campaign_id_idx" ON "contacts" USING btree ("campaign_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contacts_status_idx" ON "contacts" USING btree ("status");
--> statement-breakpoint
DO $$ BEGIN
  CREATE UNIQUE INDEX IF NOT EXISTS "credit_transactions_user_reference_unique" ON "credit_transactions" USING btree ("user_id","reference") WHERE reference IS NOT NULL;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN unique_violation THEN RAISE WARNING 'skipped credit_transactions_user_reference_unique: duplicate (user_id, reference) rows exist - dedupe and re-run'; END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "credit_transactions_user_id_idx" ON "credit_transactions" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "credit_transactions_created_at_idx" ON "credit_transactions" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agents_user_id_idx" ON "incoming_agents" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agents_credential_id_idx" ON "incoming_agents" USING btree ("eleven_labs_credential_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agents_eleven_labs_agent_id_idx" ON "incoming_agents" USING btree ("eleven_labs_agent_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "phone_numbers_user_id_idx" ON "phone_numbers" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "phone_numbers_status_idx" ON "phone_numbers" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "phone_numbers_next_billing_date_idx" ON "phone_numbers" USING btree ("next_billing_date");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plivo_calls_user_id_idx" ON "plivo_calls" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plivo_calls_campaign_id_idx" ON "plivo_calls" USING btree ("campaign_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plivo_calls_contact_id_idx" ON "plivo_calls" USING btree ("contact_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plivo_calls_status_idx" ON "plivo_calls" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plivo_calls_created_at_idx" ON "plivo_calls" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plivo_calls_plivo_call_uuid_idx" ON "plivo_calls" USING btree ("plivo_call_uuid");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "refresh_tokens_user_id_idx" ON "refresh_tokens" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "refresh_tokens_expires_at_idx" ON "refresh_tokens" USING btree ("expires_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_user_id_idx" ON "sip_calls" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_campaign_id_idx" ON "sip_calls" USING btree ("campaign_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_contact_id_idx" ON "sip_calls" USING btree ("contact_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_status_idx" ON "sip_calls" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_created_at_idx" ON "sip_calls" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_external_call_id_idx" ON "sip_calls" USING btree ("external_call_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sip_calls_elevenlabs_conversation_id_idx" ON "sip_calls" USING btree ("elevenlabs_conversation_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "twilio_openai_calls_user_id_idx" ON "twilio_openai_calls" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "twilio_openai_calls_campaign_id_idx" ON "twilio_openai_calls" USING btree ("campaign_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "twilio_openai_calls_contact_id_idx" ON "twilio_openai_calls" USING btree ("contact_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "twilio_openai_calls_status_idx" ON "twilio_openai_calls" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "twilio_openai_calls_created_at_idx" ON "twilio_openai_calls" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "twilio_openai_calls_twilio_call_sid_idx" ON "twilio_openai_calls" USING btree ("twilio_call_sid");
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "plivo_phone_numbers" ADD CONSTRAINT "plivo_phone_numbers_stripe_subscription_id_unique" UNIQUE("stripe_subscription_id");
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN unique_violation THEN RAISE WARNING 'skipped plivo_phone_numbers_stripe_subscription_id_unique: duplicate stripe_subscription_id rows exist - dedupe and re-run';
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calls_campaign_id_phone_number_idx" ON "calls" USING btree ("campaign_id","phone_number");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_chunks_kb_user_idx" ON "knowledge_chunks" USING btree ("knowledge_base_id","user_id");
--> statement-breakpoint
