const API_VERSION = "v1";
const API_PREFIX = `/api/${API_VERSION}`;
const API_KEY_PREFIX = "agl_sk_";
const API_ERROR_CODES = {
  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_API_KEY: "INVALID_API_KEY",
  EXPIRED_API_KEY: "EXPIRED_API_KEY",
  INSUFFICIENT_SCOPES: "INSUFFICIENT_SCOPES",
  IP_NOT_WHITELISTED: "IP_NOT_WHITELISTED",
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  // Resources
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  CONFLICT: "CONFLICT",
  // Business Logic
  INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
  AGENT_NOT_ACTIVE: "AGENT_NOT_ACTIVE",
  CAMPAIGN_NOT_ACTIVE: "CAMPAIGN_NOT_ACTIVE",
  PHONE_NUMBER_NOT_AVAILABLE: "PHONE_NUMBER_NOT_AVAILABLE",
  // Server
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
};
export {
  API_ERROR_CODES,
  API_KEY_PREFIX,
  API_PREFIX,
  API_VERSION
};
